// data.js - ~30 juegos ficticios estilo retro
const games = [
  { id:1, title:"Pixel Quest", year:1990, platform:"NES", genre:"Aventura", price:14.99, image:"img/pixel-1.png", description:"Explora mazmorras y rescata aldeanos en este clásico de 8 bits." },
  { id:2, title:"Star Racer DX", year:1992, platform:"SNES", genre:"Carreras", price:12.50, image:"img/pixel-2.png", description:"Velocidad y power-ups en pistas intergalácticas." },
  { id:3, title:"Dungeon Byte", year:1991, platform:"Genesis", genre:"RPG", price:19.99, image:"img/pixel-3.png", description:"RPG por turnos con pixel art detallado y fuego nostálgico." },
  { id:4, title:"Ninja Echo", year:1989, platform:"NES", genre:"Acción", price:9.99, image:"img/pixel-4.png", description:"Sombra y shuriken: plataformas y combate rápido." },
  { id:5, title:"Galaxy Blaster", year:1993, platform:"SNES", genre:"Shoot 'em up", price:11.99, image:"img/pixel-5.png", description:"Shooter vertical con oleadas y jefes gigantes." },
  { id:6, title:"Castle Builder", year:1994, platform:"PC", genre:"Estrategia", price:8.99, image:"img/pixel-6.png", description:"Gestiona recursos y defiende tu reino pixelado." },
  { id:7, title:"Samurai Dawn", year:1992, platform:"Genesis", genre:"Lucha", price:15.00, image:"img/pixel-7.png", description:"Duelo a duelo en arenas clásicas de 16 bits." },
  { id:8, title:"Mystic Runner", year:1995, platform:"SNES", genre:"Plataformas", price:10.00, image:"img/pixel-8.png", description:"Plataformas y saltos con magia retro." },
  { id:9, title:"Retro Kart", year:1994, platform:"SNES", genre:"Carreras", price:13.50, image:"img/pixel-9.png", description:"Karts y power-ups en pistas inspiradas en los clásicos." },
  { id:10, title:"Cyber Punket", year:1991, platform:"Amiga", genre:"Aventura", price:6.99, image:"img/pixel-10.png", description:"Aventura point-and-click en una ciudad futurista pixelada." },
  { id:11, title:"Dragon Fall", year:1990, platform:"NES", genre:"RPG", price:17.50, image:"img/pixel-11.png", description:"Viaja por un mundo de dragones y hechicería." },
  { id:12, title:"Sky Fortress", year:1993, platform:"Genesis", genre:"Shoot 'em up", price:9.50, image:"img/pixel-12.png", description:"Defiende tu fortaleza voladora contra flotas enemigas." },
  { id:13, title:"Puzzle Pop", year:1992, platform:"Game Boy", genre:"Puzzle", price:4.99, image:"img/pixel-13.png", description:"Relajante pero desafiante, encaja piezas y supera niveles." },
  { id:14, title:"Alien Harvest", year:1994, platform:"PC", genre:"Simulación", price:7.99, image:"img/pixel-14.png", description:"Gestiona una granja en un planeta lejano." },
  { id:15, title:"Blade Riders", year:1995, platform:"SNES", genre:"Acción", price:12.00, image:"img/pixel-15.png", description:"Combate montado en motos retro-futuristas." },
  { id:16, title:"Metro Detective", year:1990, platform:"Amiga", genre:"Aventura", price:5.99, image:"img/pixel-16.png", description:"Investiga crímenes en estaciones subterráneas pixeladas." },
  { id:17, title:"Hero's Code", year:1993, platform:"Genesis", genre:"RPG", price:16.99, image:"img/pixel-17.png", description:"Un grupo de héroes se enfrenta a una amenaza digital." },
  { id:18, title:"Bomber Bits", year:1988, platform:"NES", genre:"Arcade", price:6.50, image:"img/pixel-18.png", description:"Explosiones y estrategia rápida en niveles compactos." },
  { id:19, title:"Cosmo Tennis", year:1992, platform:"SNES", genre:"Deportes", price:8.50, image:"img/pixel-19.png", description:"Tenis arcade con pelotas que rebotan en gravedad variable." },
  { id:20, title:"Phantom Blade", year:1991, platform:"Genesis", genre:"Acción", price:11.20, image:"img/pixel-20.png", description:"Espadas y fantasmas en niveles sombríos." },
  { id:21, title:"Solar Quest", year:1993, platform:"PC", genre:"Aventura", price:9.99, image:"img/pixel-21.png", description:"Explora sistemas solares y resuelve misterios antiguos." },
  { id:22, title:"Turbo Chef", year:1994, platform:"SNES", genre:"Arcade", price:5.00, image:"img/pixel-22.png", description:"Cocina rápido y atiende clientes en tiempo récord." },
  { id:23, title:"Shadow Ops", year:1995, platform:"Genesis", genre:"Acción", price:14.00, image:"img/pixel-23.png", description:"Operaciones tácticas en escenarios de alta tensión." },
  { id:24, title:"Frostbite Isles", year:1990, platform:"NES", genre:"Plataformas", price:10.99, image:"img/pixel-24.png", description:"Escala islas congeladas y esquiva trampas heladas." },
  { id:25, title:"Neo Hoops", year:1992, platform:"SNES", genre:"Deportes", price:7.75, image:"img/pixel-25.png", description:"Baloncesto arcade con personajes exagerados." },
  { id:26, title:"Arcane Tower", year:1991, platform:"Genesis", genre:"Puzzle", price:6.25, image:"img/pixel-26.png", description:"Rompecabezas mágicos dentro de una torre encantada." },
  { id:27, title:"Robo Rampage", year:1994, platform:"PC", genre:"Acción", price:13.49, image:"img/pixel-27.png", description:"Pilota un robot y destruye legiones enemigas." },
  { id:28, title:"Viking Voyage", year:1989, platform:"NES", genre:"Aventura", price:9.49, image:"img/pixel-28.png", description:"Navega, descubre tesoros y combate en altamar." },
  { id:29, title:"Echo Rally", year:1993, platform:"SNES", genre:"Carreras", price:11.99, image:"img/pixel-29.png", description:"Rally retro con circuitos técnicos y mucha nitro." },
  { id:30, title:"Tiny Titans", year:1995, platform:"Game Boy", genre:"Plataformas", price:4.25, image:"img/pixel-30.png", description:"Microaventuras y grandes retos en niveles breves." }
];
